name: build

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
    paths-ignore: [ "README.md", "history.md", "release-notes.md" ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and/or Test
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        lazarus-versions: [ stable, 2.0.12, 2.0.10 ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install GDBM
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      run: |
        sudo apt update
        sudo apt install libgdbm-dev -y

    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3.0.16
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}

    - name: Build the Main App (Windows)
      if: ${{ matrix.operating-system == 'windows-latest' }}
      run: lazbuild -B --bm=Release "src/gnudbm.lpi"

    - name: Build the Main App GTK2 (Ubuntu)
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      run: |
        lazbuild -B --bm=Release "src/gnudbm.lpi"
        mv bin/gnudbm bin/gnudbm-gtk2

    - name: Build the Main App Qt5 (Ubuntu)
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      run: |
        sudo apt update
        sudo apt install libqt5pas-dev -y
        lazbuild -B --bm=Release --ws=qt5 "src/gnudbm.lpi"
        mv bin/gnudbm bin/gnudbm-qt5

    - name: Build the Main App (macOS)
      if: ${{ matrix.operating-system == 'macos-latest' }}
      run: lazbuild -B --bm=Release --ws=cocoa "src/gnudbm.lpi"

    - name: Upload binary (Windows)
      if: ${{ (matrix.operating-system == 'windows-latest') ) }}
      uses: actions/upload-artifact@v2
      with:
        name: gnudbm
        path: bin/gnudbm.exe

    - name: Upload binary (Ubuntu)
      if: ${{ (matrix.operating-system == 'ubuntu-latest') ) }}
      uses: actions/upload-artifact@v2
      with:
        name: gnudbm
        path: bin/gnudbm-*

  package-release:
    if: contains(github.ref, '/tags/')

    name: Package and create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Download the Release binary
      uses: actions/download-artifact@v2

    - name: List files
      run: ls -alF gnudbm

    - name: Create release files
      run: |
        cd gnudbm
        chmod +x gnudbm-*
        tar -zcvf gnudbm-GTK2-${{ steps.vars.outputs.tag }}-x86_64-linux.tar.gz gnudbm-gtk2
        tar -zcvf gnudbm-Qt5-${{ steps.vars.outputs.tag }}-x86_64-linux.tar.gz gnudbm-qt5
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        name: TestRestartApplication ${{ steps.vars.outputs.tag }}
        body_path: release-notes.md
        files: |
          gnudbm/*.tar.gz
          gnudbm/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
